
const poldb = [
  {
    __ctim: "25-08-2024T11:16",
    lnk: "https://channelstv.com/2024/08/25/telegram-owner-pavel-durov-arrested-at-french-airport/",
    hdl: "Telegram Owner Pavel Durov Arrested At French Airport",
    imgSrc: "https://www.channelstv.com/wp-content/uploads/2024/08/Pavel-Durov.jpg",
    tag: "free speech, France, Durov, Telegram",
  },
  {
    __ctim: 11.06,
    lnk: "https://reuters.com/world/middle-east/turkey-inflation-hit-685-ahead-election-blow-ruling-party-2024-04-03/?taid=660d251fb085f20001695c05&utm_campaign=trueAnthem:+Trending+Content&utm_medium=trueAnthem&utm_source=twitter",
    hdl: "Turkey inflation hit 68.5% ahead of election blow to ruling party",
    imgSrc: "https://www.reuters.com/resizer/v2/https%3A%2F%2Fcloudfront-us-east-2.images.arcpublishing.com%2Freuters%2FSFBRES2NRJMALJBZSHNHOTIIZ4.jpg?auth=d11097b67ef1e48f043eb7752ee08403f129642f7678971b30694beca1eb335e&width=960&quality=80",
    tag: "election,inflation,ruling-party,turkey",
  },
  {
    __ctim: 10.23,
    lnk: "https://reuters.com/world/africa/senegal-president-faye-appoints-ally-sonko-prime-minister-2024-04-02/",
    hdl: "Senegal President Faye appoints ally Sonko as prime minister",
    imgSrc: "https://www.reuters.com/resizer/v2/QWBEGZQLXZI4FB5OPGV3HHNHC4.jpg?auth=de4d17a730659db3c66214ebe36cb9bd6adbd5b2884a208e8e3aa3a631feed90&width=1200&quality=80",
    tag: "senegal,bassirou,sonko,darkar,appointment",
  },
  {
    __ctim: 10.18,
    lnk: "https://reuters.com/world/africa/ugandas-constitutional-court-upholds-anti-homosexuality-law-2024-04-03/?taid=660d13902d12050001adfc8f&utm_campaign=trueAnthem:+Trending+Content&utm_medium=trueAnthem&utm_source=twitter",
    hdl: "Uganda top court declines to block Anti-Homosexuality law but sees rights infringed",
    imgSrc: "https://www.reuters.com/resizer/v2/74VPRD26DVN4DMBFWYQ3XKZKWM.jpg?auth=4cc299a024fadef84f7bd35a59f0dc57ec0bc91b02c0ee53edf592cfd5659301&width=960&quality=80",
    tag: "Anti-homosexuality,lgbtq,law,court,uganda",
  },
  {
    __ctim: 22.35,
    lnk: "https://reuters.com/world/africa/senegal-factions-should-consult-over-election-timing-government-says-2024-02-16/",
    hdl: "Senegal's Sall promises to hold delayed presidential vote as soon as possible",
    imgSrc: "https://www.reuters.com/resizer/IcTpijxfIMtpo7aLBdgo2DKD_Do=/960x0/filters:quality(80)/cloudfront-us-east-2.images.arcpublishing.com/reuters/EWKH3TEQPBMB3L76BFFCI7QQVU.jpg",
    tag: "election,senegal,postpone",
  },
  {
    __ctim: 19.16,
    lnk: "https://bbc.com/news/live/world-68316979?at_medium=social&at_link_id=83676B2A-CCF4-11EE-965D-F00CAAF30DC0&at_format=link&at_link_origin=BBCBreaking&at_bbc_team=editorial&at_campaign_type=owned&at_link_type=web_link&at_campaign=Social_Flow&at_ptr_name=twitter",
    hdl: "In Navalny address, Biden takes aim at Trump and Republicans",
    imgSrc: "https://ichef.bbci.co.uk/live-experience/cps/624/cpsprodpb/vivo/live/images/2024/2/16/fd4e7182-9f73-4d50-8216-f4feb06ffbf9.jpg",
    tag: "putin,biden,opposition,russia",
  },
  {
    __ctim: 4.05,
    lnk:"https://bbc.com/news/world-europe-68305050?xtor=AL-72-%5Bpartner%5D-%5Bbbc.news.twitter%5D-%5Bheadline%5D-%5Bnews%5D-%5Bbizdev%5D-%5Bisapi%5D&at_link_origin=BBCNews&at_campaign_type=owned&at_link_type=web_link&at_medium=social&at_campaign=Social_Flow&at_bbc_team=editorial&at_link_id=3B852EE2-CC76-11EE-BB70-1B8C4B3AC5C4&at_format=link&at_ptr_name=twitter",
    hdl: "The KGB spy who rubbed shoulders with French elites for decades",
    imgSrc: "https://ichef.bbci.co.uk/news/800/cpsprodpb/12EE0/production/_132663577_gettyimages-1437384222.jpg.webp",
    tag: "kgb,spies,espionage,france,elites",
  },
  {
    __ctim: 3.47,
    lnk: "https://reuters.com/technology/google-launch-anti-misinformation-campaign-ahead-eu-elections-2024-02-16/?utm_source=twitter&utm_medium=Social",
    hdl: "Exclusive: Google to launch anti-misinformation campaign ahead of EU elections",
    imgSrc: "https://www.reuters.com/resizer/zletQOrAI5BczfHumO5vE1Qo6iM=/960x0/filters:quality(80)/cloudfront-us-east-2.images.arcpublishing.com/reuters/ON76UOQCJZPLHAVIYHRVWRZBMI.jpg",
    tag: "google,eu,censorship,elections",
  },
  {
    __ctim: 3.27,
    lnk:"https://www.bbc.com/news/world-europe-68313306?xtor=AL-72-%5Bpartner%5D-%5Bbbc.news.twitter%5D-%5Bheadline%5D-%5Bnews%5D-%5Bbizdev%5D-%5Bisapi%5D&at_link_origin=BBCWorld&at_link_type=web_link&at_campaign_type=owned&at_medium=social&at_campaign=Social_Flow&at_format=link&at_bbc_team=editorial&at_link_id=529C5C3A-CC72-11EE-BB70-1B8C4B3AC5C4&at_ptr_name=twitter",
    hdl: "Ukraine Russia war: US warns Avdiivka could fall",
    imgSrc: "https://ichef.bbci.co.uk/news/800/cpsprodpb/E4B2/production/_132664585_smokereuters.jpg.webp",
    tag: "war,ukraine,russia,us",
  },
  {
    __ctim: 3.16,
    lnk: "https://tribuneonlineng.com/experts-stakeholders-to-discuss-climate-finance-at-caaf24-webinar/?utm_term=Autofeed&utm_medium=Social&utm_source=Twitter#Echobox=1708047068",
    hdl: "Experts, stakeholders to discuss climate finance at CAAF24 webinar",
    imgSrc: "https://tribuneonlineng.com/wp-content/uploads/2023/05/Climate-Change.jpg",
    tag: "climate,environment,africa,webinar,CAA",
  },
  {
    __ctim: 3.13,
    lnk: "https://www.unicef.org/press-releases/14-billion-children-globally-missing-out-basic-social-protection-according-latest",
    hdl: "1.4 billion children globally missing out on basic social protection, according to latest data",
    imgSrc: "https://www.unicef.org/sites/default/files/styles/press_release_feature/public/UN0685801%205%20girls.jpg.webp?itok=QvRU90_q",
    tag: "children,unicef,social,protection",
  },
  {
    __ctim: 12.28,
    lnk: "https://www.channelstv.com/2024/02/15/why-are-indias-farmers-protesting-again/",
    hdl: "Why Are India’s Farmers Protesting Again?",
    imgSrc: "https://www.channelstv.com/wp-content/uploads/2024/02/Farmers-in-India-Delhi-Chalo-March-to-Delhi-New-Delhi-on-Republic-Day-2.jpg",
    tag: "agric,farmers,protest",
  },
  {
    __ctim: 12.09,
    lnk: "https://www.vanguardngr.com/2024/02/putin-says-he-prefers-more-predictable-biden-over-trump/",
    hdl: "Putin says he prefers more ‘predictable’ Biden over Trump",
    imgSrc: "https://cdn.vanguardngr.com/wp-content/uploads/2024/02/image-385.png",
    tag: "putin,biden,trump",
  },
  {
    __ctim: 11.44,
    lnk: "https://bbc.com/news/uk-68288727?xtor=AL-72-%5Bpartner%5D-%5Bbbc.news.twitter%5D-%5Bheadline%5D-%5Bnews%5D-%5Bbizdev%5D-%5Bisapi%5D&at_link_id=0EFB4E02-CBA3-11EE-922C-C1DE4B3AC5C4&at_format=link&at_ptr_name=twitter&at_link_origin=BBCNews&at_bbc_team=editorial&at_campaign_type=owned&at_medium=social&at_link_type=web_link&at_campaign=Social_Flow",
    hdl: "UK antisemitic hate incidents hit new high in 2023, says charity",
    imgSrc: "https://ichef.bbci.co.uk/news/800/cpsprodpb/184B0/production/_132640599_gettyimages-143070453.jpg.webp",
    tag: "antisemitism,uk,jews",
  },
  {
    __ctim: 6.45,
    lnk: "https://nairametrics.com/2024/02/15/fg-signs-mou-to-receive-2000-tractors-annually-for-5-years-to-boost-mechanised-farming/",
    hdl: "FG signs MoU to receive 2000 tractors annually for 5 years to boost mechanised farming",
    imgSrc: "https://nairametrics.com/wp-content/uploads/2023/10/American-firm-John-Deere-to-establish-tractor-assembly-plant-in-Nigeria-678x375.jpeg",
    tag: "agriculture,farming,food",
  },
  {
    __ctim: 6.41,
    lnk: "https://cdn.vanguardngr.com/wp-content/uploads/2018/08/housing-089.jpg",
    hdl: "‘Student loan scheme likely to be launched in three weeks’- Gbajabiamila",
    imgSrc: "https://nairametrics.com/wp-content/uploads/2023/06/Femi-Gbajabiamila-700x375.jpg",
    tag: "education,loan scheme",
  },
  {
    __ctim:5.23,
    lnk: "https://edition.cnn.com/2024/02/14/africa/un-concerned-about-tense-situation-in-senegal-intl/index.html",
    hdl: "UN raises alarm over escalating tensions in Senegal after election delay",
    imgSrc: "https://media.cnn.com/api/v1/images/stellar/prod/08-gettyimages-1978581441.JPG?c=16x9&q=h_383,w_680,c_fill/f_webp",
    tag:"election,senegal,protest",
  },
  {
    __ctim: 5.17,
    lnk: "https://edition.cnn.com/2024/02/14/asia/indonesia-election-prabowo-subianto-intl-hnk/index.html",
    hdl: "Ex-army strongman leader claims victory in Indonesian presidential election",
    imgSrc: "https://media.cnn.com/api/v1/images/stellar/prod/gettyimages-1956378265.jpg?c=16x9&q=h_383,w_680,c_fill/f_webp",
    tag: "election,indonesia",
  },
  {
    __ctim:4.49,
    lnk: "https://www.bbc.com/news/world-australia-68302206?xtor=AL-72-%5Bpartner%5D-%5Bbbc.news.twitter%5D-%5Bheadline%5D-%5Bnews%5D-%5Bbizdev%5D-%5Bisapi%5D&at_campaign=Social_Flow&at_medium=social&at_link_type=web_link&at_ptr_name=twitter&at_link_origin=BBCNews&at_bbc_team=editorial&at_link_id=F8C37D7C-CBAB-11EE-922C-C1DE4B3AC5C4&at_format=link&at_campaign_type=owned",
    hdl: "Julian Assange: Australian politicians call for release of WikiLeaks founder",
    imgSrc: "https://ichef.bbci.co.uk/news/800/cpsprodpb/F393/production/_132655326_7776a5e4221e985e860d601269976c0859cd83320_139_3233_18181000x563.jpg.webp",
    tag: "espionage,legal,wikileaks",
  },
  {
    __ctim: 4.48,
    lnk: "https://www.thedailystar.net/news/world/news/biden-protects-palestinians-deportation-humanitarian-reasons-3544256",
    hdl: "Biden protects Palestinians from deportation for 'humanitarian' reasons",
    imgSrc: "https://tds-images.thedailystar.net/sites/default/files/styles/big_202/public/images/2023/10/24/olfa3mkipjp7hbxywdk4yko6fm.jpg",
    tag: "deportation,war",
  },
  {
    __ctim:23444,
    lnk: "https://www.bbc.com/news/world-europe-68293760?xtor=AL-72-%5Bpartner%5D-%5Bbbc.news.twitter%5D-%5Bheadline%5D-%5Bnews%5D-%5Bbizdev%5D-%5Bisapi%5D&at_format=link&at_link_type=web_link&at_ptr_name=twitter&at_campaign=Social_Flow&at_bbc_team=editorial&at_campaign_type=owned&at_medium=social&at_link_origin=BBCWorld&at_link_id=B4ACD1A0-CB52-11EE-BBF9-73894B3AC5C4",
    hdl:"Nicolas Sarkozy gets six months for illegal campaign funding",
    imgSrc: "https://ichef.bbci.co.uk/news/800/cpsprodpb/7DD7/production/_132651223_2a65f70dac4495fc10f3c17c36badcb7ddfe1df00_273_2382_13402382x1340.jpg.webp",
    tag:"election",
  },
  {
    __ctim:  1234,
    lnk: "https://www.premiumtimesng.com/news/top-news/668473-ghanas-president-reshuffles-cabinet-10-months-to-general-elections.html?utm_campaign=twitter&utm_medium=twitter&utm_source=twitter",
    hdl: "Ghana’s President reshuffles cabinet 10 months to general elections",
    imgSrc: "https://media.premiumtimesng.com/wp-content/files/2020/04/Nana-Akufo-Addo-768x512.jpg",
    tag:"politics",
  },
  {
    __ctim: 12345,
    lnk: "https://nairametrics.com/2024/02/13/uk-to-sign-new-trade-deal-with-nigeria-to-allow-u-k-lawyers-practise-in-nigeria/",
    hdl: "UK to sign new trade deal with Nigeria, to allow U.K lawyers practise in Nigeria",
    imgSrc: "https://nairametrics.com/wp-content/uploads/2024/01/Screenshot-2024-01-22-061718.png",
    tag: "law",
  },
  {
    __ctim: 9743,
    lnk: "https://www.bbc.com/news/world-middle-east-68281213?xtor=AL-72-%5Bpartner%5D-%5Bbbc.news.twitter%5D-%5Bheadline%5D-%5Bnews%5D-%5Bbizdev%5D-%5Bisapi%5D&at_campaign_type=owned&at_format=link&at_ptr_name=twitter&at_bbc_team=editorial&at_medium=social&at_campaign=Social_Flow&at_link_type=web_link&at_link_id=82C0A6B0-CA28-11EE-8E58-A6ABD0B4AF07&at_link_origin=BBCWorld",
    hdl: "Israel Gaza: Biden says Israel must protect vulnerable in Rafah",
    imgSrc: "https://ichef.bbci.co.uk/news/800/cpsprodpb/2D3E/production/_132628511_e51369c5777ba4fa8575c97a3bed2c110178e280-1.jpg.webp",
    tag: "war",
  },
  {
    __ctim: 46788,
    lnk: "https://www.channelstv.com/2024/02/13/bandits-kill-four-persons-including-policemen-in-zamfara-abduct-40-others/",
    hdl: "Bandits have killed two policemen, and two other residents and abducted about forty persons in an attack on Kasuwa-Daji Town under the Kaura-Namoda Local Government Area in Zamfara State. ",
    imgSrc: "https://www.channelstv.com/wp-content/uploads/2021/09/Gunmen-Gunmennnnnnnnnnnnnnnn2.jpg",
    tag: "security",
  },
];


export default poldb;

