const scidb = [
  {
    __ctim: 10.08,
    lnk: "https://phys.org/news/2024-04-nasa-clock-moon-seconds-faster.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "NASA wants to come up with a new clock for the moon, where seconds tick away faster",
    imgSrc: "https://scx1.b-cdn.net/csz/news/800a/2024/nasa-wants-to-come-up.jpg?f=webp",
    tag: "space, astronomy,exploration,moon,time,clock",
  },
  {
    __ctim: 19.00,
    lnk: "https://bbc.com/news/articles/c80k211w7z5o?xtor=AL-72-%5Bpartner%5D-%5Bbbc.news.twitter%5D-%5Bheadline%5D-%5Bnews%5D-%5Bbizdev%5D-%5Bisapi%5D&at_bbc_team=editorial&at_link_origin=BBCScienceNews&at_campaign_type=owned&at_medium=social&at_link_id=74055304-EEBE-11EE-A4B1-C9B44B3AC5C4&at_campaign=Social_Flow&at_link_type=web_link&at_format=link&at_ptr_name=twitter",
    hdl: "Birth of endangered monkey a sign of hope - zoo",
    imgSrc: "https://ichef.bbci.co.uk/news/640/cpsprodpb/f3e4/live/4d260660-eeab-11ee-848d-8502df76512f.jpg.webp",
    tag: "endangered,species,monkey",
  },
  {
    __ctim: 18.19,
    lnk:"https://newscientist.com/article/2422899-cannabis-vaping-liquids-contain-lead-and-other-toxic-metals/?utm_term=Autofeed&utm_campaign=echobox&utm_medium=social&utm_source=Twitter#Echobox=1711817355",
    hdl: "Cannabis vaping liquids contain lead and other toxic metals.",
    imgSrc: "https://images.newscientist.com/wp-content/uploads/2024/03/18182441/SEI_196546591.jpg?width=700",
    tag: "toxic,cannabis,vaping,vape",
  },
  {
    __ctim: 19.26,
    lnk:" https://phys.org/news/2024-02-species-pirate-spiders-south-atlantic.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "New species of pirate spiders discovered on South Atlantic island",
    imgSrc: "https://scx1.b-cdn.net/csz/news/800a/2024/new-species-of-pirate-2.jpg?f=webp",
    tag: "evolution,ecology,spiders",
  },
  {
    __ctim: 9.37,
    lnk: "https://science.org/content/article/counting-nemo-clownfish-may-be-capable-simple-math?utm_medium=ownedSocial&utm_source=Twitter&utm_campaign=NewsfromScience",
    hdl: "Clownfish may be capable of simple math",
    imgSrc: "https://www.science.org/do/10.1126/science.zz4qd8m/full/_20240201_on_clownfish-1706821556973.jpg",
    tag: "clownfish,math,three,ocean,life",
  },
  {
    __ctim: 4.08,
    lnk: "https://phys.org/news/2024-02-gibraltar-subduction-zone-invading-atlantic.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "How do oceans start to close? New study suggests the Atlantic may 'soon' enter its declining phase",
    imgSrc: "https://scx1.b-cdn.net/csz/news/800a/2024/how-do-oceans-start-to.jpg?f=webp",
    tag: "climate,environment,ocean",
  },
  {
    __ctim: 3.38,
    lnk: "https://newscientist.com/article/2416727-bacteria-could-help-turn-co2-to-rock-under-extreme-conditions/?utm_term=Autofeed&utm_campaign=echobox&utm_medium=social&utm_source=Twitter#Echobox=1708046226",
    hdl: "Bacteria could help turn CO2 to rock under extreme conditions",
    imgSrc: "https://images.newscientist.com/wp-content/uploads/2024/02/14145226/SEI_191286805.jpg?width=700",
    tag: "biotechnology,microbes,earth",
  },
  {
    __ctim: 3.33,
    lnk: "https://newscientist.com/article/mg26134773-000-why-physicists-are-rethinking-the-route-to-a-theory-of-everything/?utm_term=Autofeed&utm_campaign=echobox&utm_medium=social&utm_source=Twitter#Echobox=1708046225",
    hdl: "Why physicists are rethinking the route to a theory of everything",
    imgSrc: "https://images.newscientist.com/wp-content/uploads/2024/02/06160745/final-theory-of-everything.jpg?width=700",
    tag: "theory,everything,physics",
  },
  {
    __ctim: 3.07,
    lnk: "https://phys.org/news/2024-02-thermometry-method-reveals-compressing-gas.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "New thermometry method reveals that compressing a gas may lead to cooling",
    imgSrc: "https://scx1.b-cdn.net/csz/news/800a/2024/new-thermometry-method.jpg?f=webp",
    tag: "quantum,physics,thermometry",
  },
  {
    __ctim: 2.53,
    lnk: "https://phys.org/news/2024-02-deforested-africa.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "Mapping how deforested land in Africa is used",
    imgSrc: "https://scx1.b-cdn.net/csz/news/800a/2024/how-is-deforested-land.jpg?f=webp",
    tag: "earth,environment,africa,deforestation",
  },
  {
    __ctim: 2.50,
    lnk: "https://newscientist.com/article/2371780-the-science-and-side-effects-behind-the-semaglutide-weight-loss-drugs/?utm_term=Autofeed&utm_campaign=echobox&utm_medium=social&utm_source=Twitter#Echobox=1708023370",
    hdl: "The science and side effects behind the semaglutide weight loss drugs",
    imgSrc: "https://images.newscientist.com/wp-content/uploads/2024/02/06161756/SEI_190303158.jpg?width=700",
    tag: "semaglutide,side-effects,drugs",
  },
  {
    __ctim: 2.42,
    lnk: "https://medicalxpress.com/news/2024-02-neural-brain-speech-echo.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "Neural activity study shows the brain processes direct speech and its echo separately",
    imgSrc: "https://scx1.b-cdn.net/csz/news/800a/2024/the-brain-processes-sp.jpg?f=webp",
    tag: "neuroscience,biotechnology,brain,sound",
  },
  {
    __ctim: 12.53,
    lnk: "https://phys.org/news/2024-02-scientists-largest-magnetic-fields-galaxy.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "Scientists map the largest magnetic fields in galaxy clusters using synchrotron intensity gradient",
    imgSrc: "https://scx2.b-cdn.net/gfx/news/hires/2024/scientists-have-mapped.jpg",
    tag: "space,magnets,fields,force,galaxies",
  },
  {
    __ctim: 12.17,
    lnk: "https://punchng.com/south-korean-scientists-develop-meaty-rice/",
    hdl: "South Korean scientists develop ‘meaty rice",
    imgSrc: "https://cdn.punchng.com/wp-content/uploads/2024/02/15114943/n.png",
    tag: "food,hybrid,rice",
  },
  {
    __ctim: 6.50,
    lnk: "https://www.newscientist.com/article/2414433-slight-flight-altitude-changes-could-slash-aviations-climate-impact/?utm_term=Autofeed&utm_campaign=echobox&utm_medium=social&utm_source=Twitter#Echobox=1707972021",
    hdl: "Slight flight altitude changes could slash aviation's climate impact",
    imgSrc: "https://images.newscientist.com/wp-content/uploads/2024/01/29204642/SEI_189196398.jpg?width=700",
    tag: "environment,climate change,aviation",
  },
  {
    __ctim: 6.23,
    lnk: "https://phys.org/news/2024-02-saturn-largest-moon-uninhabitable.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "Saturn's largest moon most likely uninhabitable",
    imgSrc: "https://scx1.b-cdn.net/csz/news/800a/2024/saturns-largest-moon-m-1.jpg?f=webp",
    tag: "astrobiology,planets",
  },
  {
    __ctim: 6.16,
    lnk: "https://www.newscientist.com/article/2417057-half-of-the-amazon-may-be-pushed-to-climate-tipping-point-by-2050/?utm_term=Autofeed&utm_campaign=echobox&utm_medium=social&utm_source=Twitter#Echobox=1707948744",
    hdl: "Half of the Amazon may be pushed to climate tipping point by 2050",
    imgSrc: "https://images.newscientist.com/wp-content/uploads/2024/02/14132525/SEI_191280966.jpg?width=700",
    tag: "climate change,environment",
  },
  {
    __ctim: 6.10,
    lnk: "https://medicalxpress.com/news/2024-02-epigenetic-clocks-reinvent-age.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "New epigenetic clocks reinvent how we measure age",
    imgSrc: "https://scx1.b-cdn.net/csz/news/800a/2024/new-epigenetic-clocks.jpg?f=webp",
    tag: "medicine,aging",
  },
  {
    __ctim: 5.56,
    lnk: "https://phys.org/news/2024-02-anthropologists-unveils-early-stone-plaza.html?utm_source=twitter.com&utm_medium=social&utm_campaign=v2",
    hdl: "Anthropologists' research unveils early stone plaza in the Andes",
    imgSrc: "https://scx1.b-cdn.net/csz/news/800a/2024/uw-anthropologists-res.jpg?f=webp",
    tag: "anthropology,architecture",
  },
  {
    __ctim: 5.38,
    lnk: "https://abcnews.go.com/International/half-worlds-migratory-species-decline-report-warns/story?id=107229331",
    hdl: "Nearly half of the world's migratory species are in decline, UN report warns",
    imgSrc: "https://i.abcnewsfe.com/a/1bfc8d1a-9e7d-44e2-8c98-83e3b6f7e381/humpback-whale-ap-jef-240214_1707930065649_hpEmbed_21x13.jpg",
    tag: "extinction,wildlife",
  },
  {
    __ctim: 5.21,
    lnk: "https://edition.cnn.com/2024/02/14/climate/amazon-rainforest-climate-deforestation-collapse-int/index.html",
    hdl: "The Amazon has survived changes in the climate for 65 million years. Now it’s heading for collapse, a study says",
    imgSrc: "https://media.cnn.com/api/v1/images/stellar/prod/andre-dib-12.jpg?c=16x9&q=h_383,w_680,c_fill/f_webp",
    tag: "climate change",
  },
  {
    __ctim: 5.03,
    lnk: "https://quantamagazine.org/inside-the-proton-the-most-complicated-thing-imaginable-20221019/",
    hdl: "Inside the Proton, the ‘Most Complicated Thing You Could Possibly Imagine",
    imgSrc: "https://d2r55xnwy6nx47.cloudfront.net/uploads/2022/10/PROTON_2880x1620_Lede-scaled.webp",
    tag:"atom,proton",
  },
  {
    __ctim: 4.54,
    lnk: "https://thisdaylive.com/index.php/2024/02/15/nigerians-experiencing-difficult-february-as-gas-to-power-challenge-heat-wave-worsen-nationwide",
    hdl: "Nigerians Experiencing Difficult February as Gas-to-power Challenge, Heat Wave Worsen Nationwide",
    imgSrc: "https://global.ariseplay.com/amg/www.thisdaylive.com/uploads/NiMet.png?mrf-size=m",
    tag: "weather,climate change",

  },
  {
    __ctim:4.25,
    lnk: "https://bbc.com/news/business-68302228?xtor=AL-72-%5Bpartner%5D-%5Bbbc.news.twitter%5D-%5Bheadline%5D-%5Bnews%5D-%5Bbizdev%5D-%5Bisapi%5D&at_link_origin=BBCScienceNews&at_ptr_name=twitter&at_bbc_team=editorial&at_link_id=0955A1C6-CBAF-11EE-922C-C1DE4B3AC5C4&at_format=link&at_campaign_type=owned&at_campaign=Social_Flow&at_link_type=web_link&at_medium=social",
    hdl: "SpaceX's legal home moved to Texas, says Elon Musk",
    imgSrc: "https://ichef.bbci.co.uk/news/800/cpsprodpb/4047/production/_132655461_gettyimages-1984216350.jpg.webp",
    tag: "spaceX",
  }

]


export default scidb;
